src/lists/urls.py
from django.urls import path
from lists import views
urlpatterns = [
    path('new', views.new_list, name='new_list'),
    path("<int:list_id>/", views.view_list, name="view_list"),
    path("<int:list_id>/add_item", views.add_item, name="add_item"),
]

src/superlists/urls.py
from django.urls import include, path
from lists import views as list_views
urlpatterns = [
    path('', list_views.home_page, name='home'),
    path('lists/', include("lists.urls")),
]

src/lists/models.py
from django.db import models

# Create your models here.
class List(models.Model):
  pass

class Item(models.Model):
  text = models.TextField(default="")
  list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

src/lists/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from lists.models import Item, List

# Create your views here.
def home_page(request):
    return render( request, "home.html")

def view_list(request, list_id):
    our_list = List.objects.get(id=list_id)
    return render(request, "list.html", {"list": our_list})

def new_list(request):
    nulist = List.objects.create()
    Item.objects.create(text=request.POST["item_text"], list=nulist)
    return redirect(f'/lists/{nulist.id}/')

def add_item(request, list_id):
    our_list = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"], list=our_list)
    return redirect(f'/lists/{our_list.id}/')

src/lists/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do Lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="row justify-content-center p-5 bg-body-tertiary rounded-3">
				<div class="col-lg-6 text-center">
					<h1 class="display-1 mb-4">{% block header_text%}{% endblock %}</h1>
					
					<form method="POST" action="{% block form_action %}{% endblock %}">
						<input
						class="form-control-lg"
						name="item_text"
						id="id_new_item"
						placeholder="Enter a to-do item"
						/>
						{% csrf_token 	%}
					</form>
					
				</div>
			</div>

			<div class="row justify-content-center">
				<div class="col-lg-6">
					{% block table %}
					{% endblock %}
				</div>
			</div>

		</div>
	</body>
</html>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %} Start a new To-Do List {% endblock %}

{% block form_action %}/lists/new{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text%}Your To-Do List{% endblock %}

{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}

{% block table%}
		<table class="table" id="id_list_table">
			{% for item in list.item_set.all %}
				<tr><td>{{ forloop.counter}}: {{ item.text }}<td></tr>
			{% endfor %}
		</table>
{% endblock %}